"use client";

import { useState } from "react";
import { Eye, EyeOff, ChevronDown, ChevronUp, Trash2, Plus } from "lucide-react";
import { SectionEditor } from "@/components/admin/section-editors/section-editor";
import {
  updateSectionAction,
  addSectionAction,
  deleteSectionAction,
  reorderSectionsAction,
  uploadSectionImageAction,
  seedDefaultSectionsAction,
} from "./actions";

const SECTION_LABELS: Record<string, { icon: string; label: string }> = {
  hero: { icon: "🖼️", label: "Héro / Bannière" },
  welcome: { icon: "👋", label: "Mot du maire" },
  highlights: { icon: "⭐", label: "À la une" },
  news: { icon: "📰", label: "Dernières actualités" },
  events: { icon: "📅", label: "Prochains événements" },
  gallery: { icon: "📸", label: "Galerie photos" },
  links: { icon: "🔗", label: "Liens rapides" },
  text: { icon: "📝", label: "Texte libre" },
  services: { icon: "🏛️", label: "Infos mairie" },
};

const SINGLETON_TYPES = ["hero", "welcome", "highlights", "news", "events", "links", "services"];

interface Section {
  id: string;
  section_type: string;
  visible: boolean;
  sort_order: number;
  content: Record<string, unknown>;
}

export function HomepageEditor({ initialSections }: { initialSections: Section[] }) {
  const [sections, setSections] = useState(initialSections);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [seeding, setSeeding] = useState(false);

  async function handleSeedDefaults() {
    setSeeding(true);
    await seedDefaultSectionsAction();
    window.location.reload();
  }

  async function handleToggleVisibility(id: string, currentVisible: boolean) {
    await updateSectionAction(id, { visible: !currentVisible });
    setSections((prev) => prev.map((s) => s.id === id ? { ...s, visible: !currentVisible } : s));
  }

  async function handleMoveUp(index: number) {
    if (index === 0) return;
    const newSections = [...sections];
    [newSections[index - 1], newSections[index]] = [newSections[index], newSections[index - 1]];
    setSections(newSections);
    await reorderSectionsAction(newSections.map((s) => s.id));
  }

  async function handleMoveDown(index: number) {
    if (index >= sections.length - 1) return;
    const newSections = [...sections];
    [newSections[index], newSections[index + 1]] = [newSections[index + 1], newSections[index]];
    setSections(newSections);
    await reorderSectionsAction(newSections.map((s) => s.id));
  }

  async function handleSaveContent(id: string, content: Record<string, unknown>) {
    await updateSectionAction(id, { content });
    setSections((prev) => prev.map((s) => s.id === id ? { ...s, content } : s));
  }

  async function handleUploadImage(file: File): Promise<string | null> {
    const formData = new FormData();
    formData.set("file", file);
    return uploadSectionImageAction(formData);
  }

  async function handleAddSection(type: string) {
    const maxOrder = sections.reduce((max, s) => Math.max(max, s.sort_order), -1);
    const result = await addSectionAction(type, maxOrder + 1);
    if (result.id) {
      setSections([...sections, {
        id: result.id,
        section_type: type,
        visible: true,
        sort_order: maxOrder + 1,
        content: {},
      }]);
      setExpandedId(result.id);
    }
  }

  async function handleDeleteSection(id: string) {
    if (!confirm("Supprimer cette section ?")) return;
    await deleteSectionAction(id);
    setSections((prev) => prev.filter((s) => s.id !== id));
  }

  const usedSingletonTypes = sections.map((s) => s.section_type).filter((t) => SINGLETON_TYPES.includes(t));
  const availableTypes = Object.keys(SECTION_LABELS).filter(
    (t) => !SINGLETON_TYPES.includes(t) || !usedSingletonTypes.includes(t)
  );

  if (sections.length === 0) {
    return (
      <div className="rounded-[14px] border border-[#f0e8da] bg-white p-8 text-center shadow-[0_2px_8px_rgba(140,120,80,0.08)]">
        <p className="text-[var(--muted-foreground)]">Aucune section configurée.</p>
        <button onClick={handleSeedDefaults} disabled={seeding}
          className="mt-4 rounded-lg px-6 py-2 text-sm font-medium text-white disabled:opacity-50"
          style={{ backgroundColor: "var(--theme-primary)" }}>
          {seeding ? "Création..." : "Créer les sections par défaut"}
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-3">
      {sections.map((section, index) => {
        const info = SECTION_LABELS[section.section_type] ?? { icon: "❓", label: section.section_type };
        const isExpanded = expandedId === section.id;
        const isAutoGenerated = ["news", "events", "services"].includes(section.section_type);

        return (
          <div key={section.id}
            className={`rounded-[14px] border bg-white shadow-[0_1px_4px_rgba(140,120,80,0.06)] transition-all ${
              section.visible ? "border-[#f0e8da]" : "border-gray-200 opacity-60"
            }`}>
            <div className="flex items-center gap-2 px-4 py-3">
              <div className="flex flex-col gap-0.5">
                <button onClick={() => handleMoveUp(index)} disabled={index === 0}
                  className="rounded p-0.5 text-[var(--muted-foreground)] hover:text-[var(--foreground)] disabled:opacity-20">
                  <ChevronUp size={14} />
                </button>
                <button onClick={() => handleMoveDown(index)} disabled={index === sections.length - 1}
                  className="rounded p-0.5 text-[var(--muted-foreground)] hover:text-[var(--foreground)] disabled:opacity-20">
                  <ChevronDown size={14} />
                </button>
              </div>

              <button onClick={() => setExpandedId(isExpanded ? null : section.id)}
                className="flex flex-1 items-center gap-2 text-left">
                <span className="text-lg">{info.icon}</span>
                <span className="text-sm font-medium text-[var(--foreground)]">{info.label}</span>
                {isAutoGenerated && (
                  <span className="rounded bg-[var(--theme-pin-bg)] px-1.5 py-0.5 text-[10px] font-medium" style={{ color: "var(--theme-primary)" }}>
                    Auto
                  </span>
                )}
              </button>

              <button onClick={() => handleToggleVisibility(section.id, section.visible)}
                className="rounded p-1.5 hover:bg-[#fafaf9]"
                title={section.visible ? "Masquer" : "Afficher"}>
                {section.visible
                  ? <Eye size={16} style={{ color: "var(--theme-primary)" }} />
                  : <EyeOff size={16} className="text-gray-400" />}
              </button>

              <button onClick={() => handleDeleteSection(section.id)}
                className="rounded p-1.5 text-red-400 hover:bg-red-50 hover:text-red-600">
                <Trash2 size={14} />
              </button>
            </div>

            {isExpanded && (
              <div className="border-t border-[#f0e8da] px-4 py-4">
                <SectionEditor
                  sectionType={section.section_type}
                  content={section.content}
                  onSave={(content) => handleSaveContent(section.id, content)}
                  onUploadImage={handleUploadImage}
                />
              </div>
            )}
          </div>
        );
      })}

      {availableTypes.length > 0 && (
        <div className="flex items-center gap-2">
          <select id="add-section-type" className="rounded-lg border border-[#e8dfd0] bg-[#fafaf9] px-3 py-2 text-sm">
            {availableTypes.map((type) => (
              <option key={type} value={type}>
                {SECTION_LABELS[type]?.icon} {SECTION_LABELS[type]?.label}
              </option>
            ))}
          </select>
          <button onClick={() => {
            const select = document.getElementById("add-section-type") as HTMLSelectElement;
            if (select) handleAddSection(select.value);
          }}
            className="inline-flex items-center gap-1.5 rounded-lg px-4 py-2 text-sm font-medium text-white"
            style={{ backgroundColor: "var(--theme-primary)" }}>
            <Plus size={14} /> Ajouter
          </button>
        </div>
      )}
    </div>
  );
}
